### ISSUE TITLE
Resolving folder routing

### ISSUE THREAD

**Issue by jadok** [jadok/vemsy#22]
# Feature

## Actual behavior

Right now, you will get a 404 if you try to access a page that is a folder.

## Expected behavior

If the page currently resolving is not a file then it should look to the README.md inside the folder and render it.

## TODO

- [ ] Implement a middleware before or after the routingFileMiddleware to look inside the folder
- [ ] Update the documentation in the `cli/.setup-folder/app/contents` and change the `index.md` to `README.md`  files
- [ ] Update the documentation about that feature (`cli/.setup-folder/app/contents` and README.md)
